site_name: MultiMind
repo_url: https://github.com/yourusername/multimind-agent-platform
site_url: https://yourusername.github.io/multimind-agent-platform

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist

nav:
  - Home: index.md
  - Manual:
    - Introduction: manual/01-introduction.md
    - Core Concepts: manual/02-core-concepts.md
    - Getting Started: manual/03-getting-started.md
    - Agent Capabilities: manual/04-agent-capabilities.md
    - Chat Usage: manual/05-chat-usage.md
    - Artifacts: manual/06-artifacts.md
    - Configurable Agents: manual/07-configurable-agents.md
    - Prompt Builder: manual/08-promptbuilder.md
  - Developer Guide:
    - Codebase Guide: codebase-guide.md
    - Structured LLM Calls: structured-llm-calls.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/your-public-repo
