site_name: Your Project Docs
repo_url: https://github.com/yourusername/your-public-repo
site_url: https://yourusername.github.io/your-public-repo

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.indexes
    - toc.integrate

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Configuration: getting-started/configuration.md
  - API Reference: api-reference.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/yourusername/your-public-repo
