/**
 * Enum representing all available generated schema types
 */
export enum SchemaType {
    GoalsAnalysis = 'GoalsAnalysis',
    BusinessGoal = 'BusinessGoal',
    ContentOutline = 'ContentOutline',
    OutlineSection = 'OutlineSection',
    OperationalGuide = 'OperationalGuide',
    OperationalGuideResponse = 'OperationalGuideResponse',
    ImplementationStep = 'ImplementationStep',
    QAItem = 'QAItem',
    AnswerAnalysisResponse = 'AnswerAnalysisResponse',
    EditingResponse = 'EditingResponse',
    ContentSuggestion = 'ContentSuggestion',
    SectionImprovement = 'SectionImprovement',
    FinalResponse = 'FinalResponse',
    IntakeQuestionsResponse = "IntakeQuestionsResponse",
    GoalConfirmationResponse = 'GoalConfirmationResponse',
    RefutingResponse = 'RefutingResponse',
    ResearchResponse = "ResearchResponse",
    QueriesResponse = "QueriesResponse",
    ResearchDecomposition = 'ResearchDecomposition',
    ResearchArtifactResponse = 'ResearchArtifactResponse',
    ReviewProgressResponse = 'ReviewProgressResponse',
    WritingResponse = 'WritingResponse',
    ThinkingResponse = 'ThinkingResponse',
    WebSearchResponse = 'WebSearchResponse',
    SearchQueryResponse = 'SearchQueryResponse',
    LinkSelectionResponse = 'LinkSelectionResponse',
    QuickQueriesResponse = 'QuickQueriesResponse',
    ResearchUnderstandingResponse = 'ResearchUnderstandingResponse',
    CodeExecutionResponse = 'CodeExecutionResponse',
    BrainstormResponse = 'BrainstormResponse',
    OutlineApprovalCheck = 'OutlineApprovalCheck',
    ArtifactGeneration = 'ArtifactGeneration',
    UrlExtractionResponse = 'UrlExtractionResponse',
    WebpageSummaryResponse = 'WebpageSummaryResponse'
}
