// config.ts
import dotenv from 'dotenv';
dotenv.config({ path: ['env.defaults', '.env.local', "./.env"] });

const CHROMADB_URL = process.env.CHROMADB_URL;
const CHROMA_COLLECTION = process.env.CHROMA_COLLECTION!;
const LM_STUDIO_BASE_URL = process.env.LM_STUDIO_BASE_URL!;
const CHAT_MODEL = process.env.CHAT_MODEL!;
const EMBEDDING_MODEL = process.env.EMBEDDING_MODEL!;
const WEB_RESEARCH_CHANNEL_ID = process.env.WEB_RESEARCH_CHANNEL_ID!;
const PROJECTS_CHANNEL_ID = process.env.PROJECTS_CHANNEL_ID!;
const RESEARCHER_TOKEN = process.env.RESEARCHER_TOKEN!;
const RESEARCHER_USER_ID = process.env.RESEARCHER_USER_ID!;
const MAX_SEARCHES = parseInt(process.env.MAX_SEARCHES!, 10);
const SEARXNG_URL = process.env.SEARXNG_URL!;
const ORCHESTRATOR_USER_ID = process.env.ORCHESTRATOR_USER_ID!;
const ORCHESTRATOR_TOKEN_ID = process.env.ORCHESTRATOR_TOKEN_ID!;

const LMSTUDIO_API_KEY = process.env.LMSTUDIO_API_KEY;

export { SEARXNG_URL, ORCHESTRATOR_USER_ID, ORCHESTRATOR_TOKEN_ID, LMSTUDIO_API_KEY, EMBEDDING_MODEL, PROJECTS_CHANNEL_ID, CHROMADB_URL, CHROMA_COLLECTION, LM_STUDIO_BASE_URL, CHAT_MODEL, WEB_RESEARCH_CHANNEL_ID, RESEARCHER_TOKEN, MAX_SEARCHES, RESEARCHER_USER_ID };
