name: Build Electron App

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Enable Corepack and Yarn
        run: |
          corepack enable
      
      - name: Setup Node.js and Python
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'yarn'

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel
          
      - name: Install Dependencies
        run: |
          yarn install --immutable
          
      - name: Build Web
        env:
          CI: ""
        run: |
          yarn build:web
        
      - name: Build TypeScript
        run: yarn build:electron
        
      - name: Copy Environment Files
        run: |
          cp defaults.json dist/defaults.json
        
      - name: Build Electron App
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" = "macos-latest" ]; then
            yarn electron:package --mac
          elif [ "${{ matrix.os }}" = "windows-latest" ]; then
            yarn electron:package --win
          else
            yarn electron:package --linux
          fi
        shell: bash

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-build
          path: |
            dist/*.deb
            dist/*.AppImage
            dist/*.dmg
            dist/*.exe
            dist/*.zip
          if-no-files-found: ignore
